WebUI/Models/Doctolib/RssReader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Linq;
using System.Text.RegularExpressions;


namespace WebUI.Models.Doctolib
{
    public class RssReader
    {
       
       private static string _blogURL = "http://www.castries.fr/index.php/outils/rss?idpage=23&idmetacontenu=";

        public static IEnumerable<Rss> GetRssFeed()
        {
            XDocument feedXml = XDocument.Load(_blogURL);
            var feeds = from feed in feedXml.Descendants("item")
                        select new Rss
                        {
                            Title = feed.Element("title").Value,
                            Link = feed.Element("link").Value,
                            Description = Regex.Match(feed.Element("description").Value, @"^.{1,180}\b(?<!\s)").Value,
                            
                        };
            return feeds;
        }
    }
}

WebUI/Controllers/Doctolib/RssController.cs
using Domain;
using ServicePattern;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers.Doctolib
{
    public class RssController : Controller
    {
        // GET: Rss
        public ActionResult Index()
        {
            return View();
        }
        //public ActionResult RssReader()
        //{
        //    return View(WebUI.Models.Doctolib.RssReader.GetRssFeed());
        //}
       
    }
}

WebUI/Controllers/EspaceMedecin/MedecinController.cs
using Data;
using Domain;
using Newtonsoft.Json.Linq;
using Service.EspaceMedecin;
using Service.EspacePatient;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers.EspaceMedecin
{

    public class MedecinController : Controller

    {
        ServiceAppointment sa = new ServiceAppointment();
        ServiceMedecin sm = new ServiceMedecin();
        
        // GET: Medecin
        public ActionResult Index()
        {
            //var medecin= new IEnumerable<Doctor>();
            int a=0;
               var  medecin2 = sm.GetMany().ToList();
           
            return View(medecin2);
            
            
        }
        [HttpPost]
        public ActionResult Index(string SearchString)
        {
            //var medecin= new IEnumerable<Doctor>();

            var medecin2 = sm.GetMany(p=>p.Address.Contains(SearchString));
            
            return View(medecin2);


        }


        // GET: Medecin/Details/5
        public ActionResult Details(string id)
        {
            var medecin = sm.GetById(id);
            return View(medecin);
        }
        ServiceDisponibility sd = new ServiceDisponibility();
        public ActionResult ViewDispo(String id)
        {
            var dispo = sd.geDispoByDoctorId(id);
            return View(dispo);
        }

        // GET: Medecin/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Medecin/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Medecin/Edit/5

        PiContext pi = new PiContext();
        // POST: Medecin/Edit/5
       
        // GET: Medecin/Delete/5
       
    }
}

WebUI/Views/Rss/Create.cshtml
@model WebUI.Models.Doctolib.RssModel
@*@using (Html.BeginForm()) *@
@using (Html.BeginForm("Create", "Medecin", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h2>Create </h2>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}      
        <div>
            @Html.ActionLink("Back to Flux", "RssReader")
        </div>

WebUI/Views/Rss/RssReader.cshtml
@model IEnumerable<WebUI.Models.Doctolib.Rss>

@{
    ViewBag.Title = "RssReader";
    //Layout = "~/Views/Temp/_MyLayout.cshtml";
    //Layout = "~/Views/Temp/_MyLogin.cshtml";
}

<h2>Flux RSS</h2>


@using (Html.BeginForm())
{

    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>

}
<table id="results">
    <tr>
        <th>
            First Name & last name
        </th>
        <th>
            Acts
        </th>
        <th>
          Create 
        </th>
        <th>
            Details
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="@item.Link" target="_blank">@Html.Encode(item.Title)</a>
            </td>
            <td>
                @System.Web.HttpUtility.HtmlDecode(item.Description)

            </td>
            <td>
                <a>@Html.ActionLink("  Add", "Create")</a>
            </td>
            <td>
                <a href="@item.Link" target="_blank">More</a>
            </td>
        </tr>
    }

</table>