WebUI/Controllers/EspaceMedecin/APIDoctorController.cs
using Data;
using Domain;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Service.EspaceMedecin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Http;
using System.Web.Mvc;

namespace WebUI.Controllers.EspaceMedecin
{
    public class APIDoctorController : Controller
    {
        // GET: APIDoctor

        ServiceMedecin ds = new ServiceMedecin();

            PiContext db = new PiContext();
       
        public ActionResult GetDoctors()
        {
            IList<Doctor> lcm = new List<Doctor>();
            foreach (var item in ds.GetMany())
            {
                Doctor cm = new Doctor();
                cm.Id = item.Id;
                cm.LastName = item.LastName;
                cm.FirstName = item.FirstName;
                cm.UserName = item.UserName;
                cm.Email = item.Email;
                cm.PhoneNumber = item.PhoneNumber;
                cm.UserName = item.UserName;
                cm.BirthDate = item.BirthDate;
                cm.Gender = item.Gender;
                cm.Address = item.Address;
                cm.ImageName = item.ImageName;
                cm.Speciality = item.Speciality;
                
                lcm.Add(cm);
               
            }
           
            return Json(lcm, JsonRequestBehavior.AllowGet);


        }
     
        public ActionResult DoctorDetails(String id)
        {
            Doctor sk = ds.GetById(id);
            IList<Doctor> lcm = new List<Doctor>();
            lcm.Add(sk);

            //  var sk = ds.GetById(id);
            return Json(lcm, JsonRequestBehavior.AllowGet);

        }

       
        public ActionResult DoctorSearch(string SearchString)
        {         
            IList<Doctor> lcm = new List<Doctor>();
            foreach (var item in ds.GetMany(p => p.Address.Contains(SearchString)))
            {
                Doctor cm = new Doctor();
                cm.Id = item.Id;
                cm.LastName = item.LastName;
                cm.FirstName = item.FirstName;
                cm.UserName = item.UserName;
                cm.Email = item.Email;
                cm.PhoneNumber = item.PhoneNumber;
                cm.UserName = item.UserName;             
                cm.Gender = item.Gender;
                cm.Address = item.Address;
                cm.ImageName = item.ImageName;
                lcm.Add(cm);
            }

            return Json(lcm);

        }

        ServiceDisponibility sd = new ServiceDisponibility();
       
        public ActionResult ViewDispo(String id)
        {
            
            IList<Disponibility> lcm = new List<Disponibility>();
            foreach (var item in sd.geDispoByDoctorId(id))
            {
                Disponibility cm = new Disponibility();
                cm.Description = item.Description;
                cm.StartDate = item.StartDate;
                cm.EndDate = item.EndDate;
                cm.Doctor = item.Doctor;
                lcm.Add(cm);
            }
            return Json(lcm);
        }

        //[Route("api/doctorsList")]
        //    [HttpGet]
        //    public IHttpActionResult Index()
        //    {

        //        //var sk = ds.GetMany();
        //    IList<Doctor> lcm = new List<Doctor>();
        //    foreach (var item in ds.GetMany())
        //    {
        //        Doctor cm = new Doctor();
        //        cm.Id = item.Id;
        //        cm.FirstName = item.FirstName;
        //        cm.Email = item.Email;
        //        cm.PhoneNumber = item.PhoneNumber;
        //        cm.UserName = item.UserName;
        //        cm.BirthDate = item.BirthDate;
        //        cm.Gender = item.Gender;
        //        cm.Address = item.Address;
        //        cm.ImageName = item.ImageName;
        //        lcm.Add(cm);
        //    }
        //    return Ok(lcm);
        //  //  return Json(sk);
        //}

        //    [Route("api/docteurDetails/{id}")]
        //    [HttpGet]
        //    public IHttpActionResult Details(String id)
        //    {
        //    Doctor sk = ds.GetById(id);

        //        //  var sk = ds.GetById(id);
        //        return Ok(sk);

        //    }

        //    [Route("api/doctorDel/{id}")]
        //    [HttpPost]
        //    public IHttpActionResult Delete(String id, Doctor d)
        //    {

        //        var req = ds.GetMany().Where(a => a.Id.Equals(id)).FirstOrDefault();
        //        ds.Delete(req);
        //        ds.Commit();
        //        return Ok();
        //    }

        //    [Route("api/doctorSearch/{SearchString}")]
        //    [HttpPost]
        //    public IHttpActionResult Index(string SearchString)
        //    {

        //        var medecin2 = ds.GetMany(p => p.Address.Contains(SearchString));
        //        return Ok(medecin2);
        //    }
        //ServiceDisponibility sd = new ServiceDisponibility();
        //[Route("api/dispoByDoctor/{id}")]
        //[HttpPost]
        //public IHttpActionResult ViewDispo(String id)
        //{
        //    var dispo = sd.geDispoByDoctorId(id);

        //    return Ok(dispo);
        //}

        //[Route("api/docteurDash")]
        //[HttpGet]
        //public IHttpActionResult DashboardMedecin()
        //{
        //    var medecin = ds.getDoctorByUserName(AccountController.UserCoUserName);

        //    return Ok(medecin);

        //}
        //PiContext pi = new PiContext();



        //[Route("api/docteurDash")]
        //[HttpPost]
        //public IHttpActionResult Edit([System.Web.Mvc.Bind(Include = "Id,Email,SecurityStamp,PhoneNumber, LockoutEndDateUtc,AccessFailedCount,UserName, FirstName,LastName,birthDate,Address,ImageName,Gender,Speciality")] Doctor d, HttpPostedFileBase Image)
        //{

        //    //Doctor do= new Doctor();

        //    // TODO: Add update logic here

        //    if (ModelState.IsValid)
        //    {
        //        String fileName = Path.GetFileName(Image.FileName);
        //        d.ImageName = fileName;
        //        var doctor = ds.GetMany().Single(em => em.Id == d.Id);
        //        d.PasswordHash = doctor.PasswordHash;
        //        d.SecurityStamp = doctor.SecurityStamp;

        //        pi.Entry(d).State = EntityState.Modified;
        //        pi.SaveChanges();

        //        return Ok();
        //    }
        //    //  return RedirectToAction("Index");


        //    return Ok(d);

        //}
    }
}

WebUI/Controllers/EspaceMedecin/CalenderController.cs
using DHTMLX.Scheduler.Data;
using DHTMLX.Common;
using DHTMLX.Scheduler;
using Domain;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data;
using Service.EspaceMedecin;
using DHTMLX.Scheduler.Controls;
using System.Collections;
using System.Web.UI;

namespace WebUI.Controllers.EspaceMedecin
{
    public class CalenderController : Controller
    {

        ServiceMedecin sm = new ServiceMedecin();
        // GET: Calender
        ServiceDisponibility sd = new ServiceDisponibility();
      
        public ActionResult Index()
        {
            var scheduler = new DHXScheduler(this);
            
           
             scheduler.Lightbox.Name = "Disponibility";
         
           
            //scheduler.Lightbox.Add(check);
            scheduler.TimeSpans.Add(new DHXMarkTime()
            {

                Day = DayOfWeek.Sunday,
                CssClass = "green_section",
                SpanType = DHXTimeSpan.Type.BlockEvents
            });
            scheduler.TimeSpans.Add(new DHXMarkTime()
            {
                FullWeek = false,
                Day = DayOfWeek.Saturday,
                CssClass = "red_section",// apply this css class to the section
                HTML = "LockTime", // inner html of the section
                Zones = new List<Zone>() { new Zone { Start = 15 * 60, End = 20 * 60 } },
                SpanType = DHXTimeSpan.Type.BlockEvents//if specified - user can't create event in this area
            });
            scheduler.Skin = DHXScheduler.Skins.Flat;
            scheduler.Config.first_hour = 8;
            scheduler.Config.last_hour = 20;
            scheduler.Config.time_step = 15;
           
            scheduler.EnableDynamicLoading(SchedulerDataLoader.DynamicalLoadingMode.Month);
            scheduler.LoadData = true;
            scheduler.EnableDataprocessor = true;
            //scheduler.filter_timeline = function(id, event){ return false; }
            
            return View(scheduler);
        }
        PiContext db = new PiContext();
        public ContentResult Data(DateTime from, DateTime to)
        {
            var apps = db.Disponibilities.Where(e => e.StartDate < to && e.EndDate >= from).ToList();
            return new SchedulerAjaxData(apps);
        }
        public ActionResult Save(int? id, FormCollection actionValues)
        {
            
            var action = new DataAction(actionValues);
            
            var medecin = sm.getDoctorByUserName(AccountController.UserCoUserName);
            
            try
            {
                var changedEvent = DHXEventsHelper.Bind<Disponibility>(actionValues);
                changedEvent.DoctorId = medecin.Single().Id;

                switch (action.Type)
                {
                    case DataActionTypes.Insert:
                        { if (changedEvent.StartDate >= DateTime.Now.Date)
                            {
                                changedEvent.Description = "Disponible";
                                db.Disponibilities.Add(changedEvent);
                            }
                            else
                            {
                                Response.Write("alert('You can t add disponibility in the past')");
                            }
                        }
                            break;
                    case DataActionTypes.Delete:

                        if (changedEvent.DoctorId == ((sm.getDoctorByUserName(AccountController.UserCoUserName)).Single()).Id)
                        { db.Entry(changedEvent).State = EntityState.Deleted; }
                        else
                        {
                            Response.Write("alert('You can t delete disponibility of another doctor')");
                        }
                        break;
                    default:// "update"  
                        {
                            if (changedEvent.StartDate >= DateTime.Now.Date)
                            {if (changedEvent.DoctorId == ((sm.getDoctorByUserName(AccountController.UserCoUserName)).Single()).Id)
                                { db.Entry(changedEvent).State = EntityState.Modified; }
                                else
                                {
                                    Response.Write("alert('You can t update disponibility of another doctor')");
                                }
                            }
                            else
                            {
                                Response.Write("alert('You can t update disponibility in the past')");
                            }
                        }
                            break;
                }
                db.SaveChanges();
                action.TargetId = changedEvent.Id;
            }
            catch (Exception a)
            {
                action.Type = DataActionTypes.Error;
            }

            return (new AjaxSaveResponse(action));
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebUI/Controllers/EspaceMedecin/MedecinController.cs
using Data;
using Domain;
using Newtonsoft.Json.Linq;
using Service.EspaceMedecin;
using Service.EspacePatient;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers.EspaceMedecin
{

    public class MedecinController : Controller

    {
        ServiceAppointment sa = new ServiceAppointment();
        ServiceMedecin sm = new ServiceMedecin();
        
        // GET: Medecin
        public ActionResult Index()
        {
            //var medecin= new IEnumerable<Doctor>();
            int a=0;
               var  medecin2 = sm.GetMany().ToList();
           
            return View(medecin2);
            
            
        }
        [HttpPost]
        public ActionResult Index(string SearchString)
        {
            //var medecin= new IEnumerable<Doctor>();

            var medecin2 = sm.GetMany(p=>p.Address.Contains(SearchString));
            
            return View(medecin2);


        }


        // GET: Medecin/Details/5
        public ActionResult Details(string id)
        {
            var medecin = sm.GetById(id);
            return View(medecin);
        }
        ServiceDisponibility sd = new ServiceDisponibility();
        public ActionResult ViewDispo(String id)
        {
            var dispo = sd.geDispoByDoctorId(id);
            return View(dispo);
        }

        // GET: Medecin/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Medecin/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Medecin/Edit/5

        PiContext pi = new PiContext();
        // POST: Medecin/Edit/5
       
        // GET: Medecin/Delete/5
       
    }
}

WebUI/Controllers/EspaceMedecin/MedecinDashController.cs
using Data;
using Domain;
using Service.EspaceMedecin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers.EspaceMedecin
{
    public class MedecinDashController : Controller
    {
        ServiceMedecin sm = new ServiceMedecin();
        // GET: MedecinDash
        public ActionResult DashboardMedecin()
        {
            var medecin = sm.getDoctorByUserName(AccountController.UserCoUserName);

            return View(medecin);

        }
        public ActionResult Delete(int id)
        {
            return View();
        }
        // POST: Medecin/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var req = sm.GetMany().Where(a => a.Id.Equals(id)).FirstOrDefault();
                sm.Delete(req);
                sm.Commit();
                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Edit(String id)
        {
            var doctor = sm.GetById(id);
            return View(doctor);
        }
        PiContext pi = new PiContext();

        [HttpPost]

        public ActionResult Edit([Bind(Include = "Id,Email,SecurityStamp,PhoneNumber, LockoutEndDateUtc,AccessFailedCount,UserName, FirstName,LastName,birthDate,Address,ImageName,Gender,Speciality")] Doctor d, HttpPostedFileBase Image)
        {

            //Doctor do= new Doctor();

            // TODO: Add update logic here

            if (ModelState.IsValid)
            {
                String fileName = Path.GetFileName(Image.FileName);
                d.ImageName = fileName;
                var doctor = sm.GetMany().Single(em => em.Id == d.Id);
                d.PasswordHash = doctor.PasswordHash;
                d.SecurityStamp = doctor.SecurityStamp;
               
                pi.Entry(d).State = EntityState.Modified;
                pi.SaveChanges();
               
                return RedirectToAction("DashboardMedecin");
            }
            //  return RedirectToAction("Index");


            return View(d);

        }

    }
}

WebUI/Views/EspaceMedecin/_LayoutDashMed.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@Page.Title</title>
        @RenderSection("head", required: false)
        
            <meta charset="utf-8" />
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Responsive Admin Template" />
            <meta name="author" content="RedstarHospital" />
            <title>Epione Medical Portal | Doctor Dashboard</title>
            <!-- google font -->
            <link href=@Url.Content("http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=all") rel="stylesheet" type="text/css" />
            <!-- icons -->
            <link href=@Url.Content("/Template/assets/simple-line-icons/simple-line-icons.min.css") rel="stylesheet" type="text/css" />
            <link href=@Url.Content("/Template/light/css/font-awesome.min.css") rel="stylesheet" type="text/css" />
            <link rel="stylesheet" href=@Url.Content("https://fonts.googleapis.com/icon?family=Material+Icons")>
            <!--bootstrap -->

            <link href=@Url.Content("/Template/assets/bootstrap/css/bootstrap.min.css") rel="stylesheet" type="text/css" />
            <!-- Material Design Lite CSS -->
            <link rel="stylesheet" href=@Url.Content("/Template/assets/material/material.min.css")>
            <link rel="stylesheet" href=@Url.Content("/Template/light/css/material_style.css")>
            <!-- Theme Styles -->
            <link href=@Url.Content("/Template/light/css/theme_style.css") rel="stylesheet" id="rt_style_components" type="text/css" />
            <link href=@Url.Content("/Template/light/css/plugins.min.css") rel="stylesheet" type="text/css" />
            <link href=@Url.Content("/Template/light/css/style.css") rel="stylesheet" type="text/css" />
            <link href=@Url.Content("/Template/light/css/responsive.css") rel="stylesheet" type="text/css" />
            <link href=@Url.Content("/Template/light/css/theme-color.css") rel="stylesheet" type="text/css" />
            <!-- favicon -->
            <link rel="shortcut icon" href=@Url.Content("/Template/light/img/favicon.ico") />
            <!-- start js include path -->
            <script src=@Url.Content("/Template/assets/jquery.min.js")></script>
            <script src=@Url.Content("/Template/assets/popper/popper.js")></script>
            <script src=@Url.Content("/Template/assets/jquery.blockui.min.js")></script>
            <script src=@Url.Content("/Template/assets/jquery.slimscroll.js")></script>
            <!-- bootstrap -->
            <script src=@Url.Content("/Template/assets/bootstrap/js/bootstrap.min.js")></script>
            <script src=@Url.Content("/Template/assets/bootstrap-switch/js/bootstrap-switch.min.js")></script>
            <!-- counterup -->
            <script src=@Url.Content("/Template/assets/counterup/jquery.waypoints.min.js")></script>
            <script src=@Url.Content("/Template/assets/counterup/jquery.counterup.min.js")></script>
            <!-- Common js-->
            <script src=@Url.Content("/Template/assets/app.js")></script>
            <script src=@Url.Content("/Template/assets/layout.js")></script>
            <script src=@Url.Content("/Template/assets/theme-color.js")></script>
            <!-- material -->
            <script src=@Url.Content("/Template/assets/material/material.min.js")></script>
            <!-- chart js -->
            <script src=@Url.Content("/Template/assets/chart-js/Chart.bundle.js")></script>
            <script src=@Url.Content("/Template/assets/chart-js/utils.js")></script>
            <script src=@Url.Content("/Template/assets/chart-js/home-data.js")></script>
            <!-- end js include path -->
        
    </head>
<body class="page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white white-sidebar-color logo-indigo">
    @RenderBody()

</body>
</html>

WebUI/Views/EspaceMedecin/_LayoutForCalender.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@Page.Title</title>
        @RenderSection("head", required: false)
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

    </head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Back To Profil", "DashboardMedecin", "MedecinDash", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>© @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>